server:
  port: 8081
  servlet:
    session:
      timeout: 30
  tomcat:
    uri-encoding: UTF-8

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootroot
    url: jdbc:mysql://127.0.0.1:3306/test_db?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
  jpa:
    database: MySQL
    show-sql: true
    hibernate.ddl-auto: update
  devtools:
    restart:
      enabled: true
      exclude: WEB-INF/**
      additional-paths: src/main/java
    #设置重启的目录
    #spring.devtools.restart.additional-paths: src/main/java
    #classpath目录下的WEB-INF文件夹内容修改不重启
mybatis:
  mapper-locations: classpath:mapping/*.xml

age: 19
name: zhaodabao
role: vip

personinfo:
  name: zhaoxiaobao
  age: 3
myenvironment:
  name: production

com:
  tt:
    name: testnn
    age: 22
    address[0]: beijing
    address[1]: shanghai
    address[2]: guangzhou